### ISSUE TITLE
[Bug] Inventory name floater incorrectly placed with plugin enabled

### ISSUE THREAD

**Issue by fatcatonmars** [Glyceri/FFXIVPetRenamer#15]
Unsure what they're called, but as above and video example. Does not happen when the plugin is turned off, as expected.

https://github.com/user-attachments/assets/3d4cac8a-7289-4fba-a438-1dda620deeee

**Comment by Glyceri** [comment]
Yupp, I got multiple reports of this. I will fix it when I am home later today.

**Comment by Glyceri** [comment]
Fixed in 2.3.0.4
