### ISSUE TITLE
Enemy/Party Healthbars don't decrease

### ISSUE THREAD

**Issue by decoytrix** [Glyceri/FFXIVPetRenamer#3]
...kinna. 
So When someone is damaged, part of their healthbar will change to a different shade of its normal color to reflect the amount decreased, and then go dark to show the HP that is empty. When this mod is active for me now, the health that changes color never goes black.  It made healing a run pretty much impossible.
![Capture](https://github.com/Glyceri/FFXIVPetRenamer/assets/15527419/7c92c29f-d419-4716-a62e-1b6430434c5b)
![Capture2](https://github.com/Glyceri/FFXIVPetRenamer/assets/15527419/8accd7b3-7fbd-48a7-af2f-5d002fa744b5)

**Comment by Glyceri** [comment]
This should be fixed in tonights update.
