### ISSUE TITLE
Target bar nickname not displaying for soft-target

### ISSUE THREAD

**Issue by Uragawa** [Glyceri/FFXIVPetRenamer#4]
When soft-targeting a nicknamed entity, the original name is displayed. If you click on the entity to make it a regular target, the nickname displays properly. The plugin probably needs to also check for soft-target when handling the target bar, since that's what gets displayed when a soft-target is present.

**Comment by Glyceri** [comment]
Will get fixed in a future update.

**Comment by Glyceri** [comment]
NVM, this fix was very easy. Fixed in update 1.0.1.0

**Comment by Glyceri** [comment]
Info on reopen: Realised that other players can use the soft targeting feature as well and this isnt so 'very easy' as previously stated💀and since that isn't build in, waiting until it is build in or reverse engineering to find the hook is required.

**Comment by Glyceri** [comment]
Help came. Closed for realsies thanks to the beautiful people in the Dalamud Discord.
