### ISSUE TITLE
Fps drops under unexpected circumstances

### ISSUE THREAD

**Issue by Uragawa** [Glyceri/FFXIVPetRenamer#5]
I noticed the issue a while ago but only just had the opportunity to narrow it down. With no other plugins enabled (I used the System Configuration window to check the fps) and the game running at 60fps or higher, having the Currency window open or an item tooltip on display (I initially thought it was the Inventory window, but if a blank space is selected, the issue doesn't happen; conversely, I was able to reproduce it with an item tooltip from my XHB) knocks the fps down to 45-50 on my computer. This range is the same if I uncap fps (~108 on my system) and there's no impact at lower framerates for me, which suggests it's CPU-bound. I'm running via WINE on a Linux system with a Ryzen 5 3600X CPU and my game is installed on a HDD.

**Comment by Glyceri** [comment]
Yupp, this makes a lot of sense. My code is about as unoptimized as can be. I will fix this with other optimization issues as soon as time presents itself.

**Comment by Glyceri** [comment]
Tentatively pushed a fix to Testing. Would like to hear if it is fixed.

**Comment by Uragawa** [comment]
I can no longer reproduce either scenario, even with uncapped framerate. Looks like a fix to me!

**Comment by Glyceri** [comment]
Awesommeee! I figured I would push this update early because it seemed annoying to deal with.
