### ISSUE TITLE
Crash after Killing a Boss

### ISSUE THREAD

**Issue by NevendyND** [Glyceri/FFXIVPetRenamer#7]
When i kill a Boss with a Group Rathalos normal and Praetorium Gaius the Game Crashes.

I tried to let the Crash reappear in an Unsync Fight but it didn't show up.

[dalamud_appcrash_20230902_123630_072_209892.log](https://github.com/Glyceri/FFXIVPetRenamer/files/12503800/dalamud_appcrash_20230902_123630_072_209892.log)

**Comment by Glyceri** [comment]
I've done the Group Rathalos run, and some others people have been telling me about in the Discord. Pets out, pets not out, this definitely seems to be fixed.
