### ISSUE TITLE
Pets share names

### ISSUE THREAD

**Issue by KalZakath13** [Glyceri/FFXIVPetRenamer#8]
Some pets seem to copy their names from other very similar minions.
Black Hayate seems to think it's the Mameshiba, Coeurl Kitten and Black Coeurl copy each other, and most of the Chocobo Chicks are great examples of this.  If you name the Wayward Hatchling, it names all the GC hatchlings, the Black Chocobo Chick, and the Princely Hatchling (but not the Castaway Chocobo Chick).

**Comment by Glyceri** [comment]
Fixed. Will be pushed in 1.4.1.0
<img width="818" alt="image" src="https://github.com/Glyceri/FFXIVPetRenamer/assets/78602618/0178adb5-2e03-4b27-a868-83c6c3858dc4">
